global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sql_metrics_collector'
    static_configs:
      - targets: ['host.docker.internal:8000'] 
      # host.docker.internal allows Docker container to access the host machine's localhost on Mac/Windows.
      # If on Linux, use the host IP address (e.g. 172.17.0.1)
